export const OrderStatus = [
  { id: 1, value: "Order Pending" },
  { id: 2, value: "Driver Received" },
  { id: 3, value: "Office Received" },
  { id: 4, value: "Driver Pending" },
  { id: 5, value: "Driver Pick Up" },
  { id: 6, value: "Postpone" },
  { id: 7, value: "Partially Delivered" },
  { id: 8, value: "Delivered" },
  { id: 9, value: "Cancelled" },
  { id: 10, value: "Cancelled Office Received" },
  { id: 11, value: "Partially Cancelled Office Received" },
  { id: 12, value: "Cancelled Driver Received" },
  { id: 13, value: "Partially Cancelled Driver Received" },
  { id: 14, value: "Payment Processing" },
  { id: 15, value: "Partially Payment Processing" },
  { id: 16, value: "Cancelled Supplier Received" },
  { id: 17, value: "Partially Cancelled Supplier Received" },
  { id: 18, value: "Completed" },
] as const;